In [20]:
import pandas as pd

This notebook will add coauthorship links given a folder containing a network that was outlined earlier.

In [31]:
path_to_folder = "../CFDE/"

In [32]:
for_edge = pd.read_csv(path_to_folder + "authors.published.pmids.edges.csv")

# Let us create a dictionary that maps each author to their respective pmids.
source_to_targets = for_edge.groupby('source')['target'].apply(set).to_dict()


#Create an inverted dictionary mapping targets to sources
target_to_sources = {}
for source, targets in source_to_targets.items():
    for target in targets:
        target_to_sources.setdefault(target, set()).add(source)

# Create the final dictionary mapping each source to all other sources that share at least one target
source_to_related_sources = {}
for source, targets in source_to_targets.items():
    related_sources = set()
    for target in targets:
        related_sources.update(target_to_sources[target])
    related_sources.discard(source)  # Remove the source itself
    source_to_related_sources[source] = related_sources

print(source_to_related_sources)

{0: {1472, 1473, 329}, 1: {2, 198, 1543, 1799, 1800, 585, 269, 909, 1361, 614, 1452, 1004, 109, 48, 1330, 1017, 317, 1855}, 2: {1, 198, 1543, 1799, 1800, 585, 269, 909, 1361, 614, 1452, 1004, 109, 48, 1330, 1017, 317, 1855}, 3: {1920, 382, 782, 1169, 1276, 663, 1180, 1566, 1952, 33, 1956, 1703, 1196, 1203, 1719, 185, 186, 1212, 1214, 1348, 454, 331, 1240, 1375, 1376, 100, 1509, 494, 241, 755, 1907, 380, 892, 894}, 4: {1088, 1795, 773, 137, 1225, 11, 202, 1612, 599, 600, 1627, 1889, 551, 1895, 425, 433, 1651, 629, 1782, 1783, 184, 1529, 1663}, 5: {66, 898, 804, 1892, 1128, 1545, 654, 1200, 466, 339, 1138, 1906, 1911, 830}, 6: {1409, 1673, 147, 403, 277, 537, 1564, 158, 1694, 1316, 165, 1444, 169, 43, 174, 1329, 1077, 695, 1594, 1595, 444, 1851, 1095, 73, 844, 1104, 1107, 86, 601, 1505, 1126, 1383, 744, 1645, 1009, 1269, 503}, 7: {1034, 1037, 1558, 1816, 1277, 31, 1058, 1828, 812, 1584, 568, 569, 1339, 574, 1096, 1608, 1098, 1610, 1102, 79, 1873, 597, 605, 862, 95, 1378, 356, 1639, 872, 1900, 621, 112, 1915, 123, 1916, 641, 387, 1421, 926, 159, 1185, 1699, 1190, 680, 1194, 1710, 1459, 1205, 1717, 696, 953, 1208, 189, 701, 707, 710, 1480, 971, 716, 215, 1499, 737, 483, 1767, 1015, 1533}, 8: {1345, 835, 1541, 10, 140, 204, 1358, 783, 1041, 18, 1106, 84, 346, 220, 92, 1890, 293, 1191, 937, 748, 876, 1333, 888, 1465, 1534}, 9: {900, 908, 1228, 16, 1875, 276, 1238, 984, 1817, 1311, 1567, 1631, 292, 1318, 1447, 1386, 1259, 1583, 1200, 1394, 1331, 371, 309, 1911}, 10: {1541, 8, 649, 140, 783, 1041, 18, 534, 417, 1317, 293, 1191, 937, 1333, 1465, 1345, 835, 204, 1358, 1106, 339, 84, 1749, 346, 220, 92, 1890, 748, 876, 1911, 888, 1534}, 11: {1088, 1795, 4, 773, 137, 1225, 202, 1612, 599, 600, 1627, 1889, 551, 1895, 425, 433, 1651, 629, 1782, 1783, 184, 1529, 1663}, 12: {579, 452, 365, 592, 692, 788, 1690}, 13: {352, 672, 1956, 360, 745, 1930, 399, 1135, 1681, 88, 1724}, 14: {1668, 423, 41, 297, 141, 1581, 112, 1521, 758, 215, 862, 31}, 15: {327, 1161, 1482, 1866, 652, 594, 1362, 921, 924, 106, 1202, 947, 244, 628, 1527, 1340, 253, 1022, 639}, 16: {900, 9, 908, 1228, 1875, 276, 1238, 984, 1817, 1311, 1567, 1631, 292, 1318, 1447, 1386, 1259, 1583, 1200, 1394, 1331, 371, 309, 1911}, 17: {389, 1546, 398, 1808, 148, 535, 920, 664, 156, 414, 34, 163, 1314, 1701, 1577, 1591, 1720, 1730, 1347, 324, 1858, 1352, 713, 719, 343, 1880, 1497, 1250, 1382, 615, 1002, 1130, 1388, 495, 1778, 756, 1023}, 18: {1541, 263, 8, 10, 140, 1679, 783, 1041, 1557, 667, 293, 1191, 937, 299, 819, 1333, 1465, 187, 959, 1345, 835, 204, 1358, 1106, 84, 346, 220, 92, 1890, 1637, 748, 876, 374, 888, 890, 1534}, 19: {1542, 1549, 536, 32, 1570, 35, 1064, 1065, 1067, 55, 1080, 575, 63, 1605, 1606, 588, 589, 1120, 1121, 101, 1641, 1129, 1646, 1141, 118, 117, 629, 1663, 643, 1669, 1160, 1674, 168, 685, 1217, 197, 1740, 1743, 721, 727, 217, 218, 732, 733, 222, 227, 1251, 229, 1253, 1257, 746, 1773, 751, 1782, 1783, 1272, 761, 1790, 256, 1280, 1794, 1294, 785, 789, 790, 1307, 1308, 1820, 800, 289, 803, 1832, 315, 320, 836, 1351, 845, 336, 338, 344, 1370, 1895, 1385, 874, 877, 1393, 370, 1908, 1912, 1913, 1914, 1403, 1917, 1918, 1919, 897, 1921, 1925, 1927, 1928, 393, 1419, 1935, 912, 402, 914, 916, 405, 1940, 1432, 1948, 1949, 1954, 1957, 1446, 1960, 941, 1967, 432, 1466, 955, 1467, 968, 457, 1484, 973, 976, 983, 486, 998, 1005, 1006, 1517, 1008, 1007, 1524, 1535}, 20: {164, 996, 810, 787, 473, 1692, 893, 798}, 21: {1154, 1412, 264, 650, 523, 1163, 1679, 1296, 1429, 539, 1693, 1059, 1060, 296, 427, 819, 1338, 827, 445, 972, 1495, 860, 1757, 224, 1510, 1258, 1261, 1655, 1018, 1019, 381}, 22: {675, 612, 172, 1197, 1038, 369, 1555, 1012, 1463, 1560, 1565}, 23: {160, 1313, 578, 1344, 40, 884, 1625, 507, 447}, 24: {640, 1380, 1636, 1959, 618, 1418, 1132, 1133, 1134, 1877, 1752}, 25: {488, 777, 779, 492, 1324, 1805, 1360, 1657, 1777, 1812, 1814, 1879, 760}, 26: {1089, 1218, 580, 1220, 839, 1165, 77, 1614, 207, 208, 1303, 1243, 1469, 485, 1068, 633, 1844, 821, 502, 1337, 508, 1213}, 27: {1156, 1285, 136, 776, 138, 1354, 80, 81, 1426, 596, 1111, 1239, 1305, 729, 1116, 1373, 1249, 1442, 1640, 108, 817, 951, 632, 1273}, 28: {114, 196, 1413, 1865, 1677, 542}, 29: {1538, 1667, 1028, 1672, 265, 397, 527, 1167, 1295, 794, 538, 157, 544, 1279, 1579, 1709, 1841, 818, 182, 310, 1334, 1470, 1600, 1475, 71, 1607, 1097, 1485, 82, 1746, 469, 986, 91, 1630, 1760, 230, 1000, 237, 366, 1518, 1139, 1523, 1150, 511}, 30: {384, 518, 1670, 1544, 396, 1944, 153, 410, 796, 1312, 170, 1322, 943, 1968, 1073, 178, 946, 948, 437, 1587, 823, 440, 697, 1596, 1726, 576, 577, 1734, 1863, 1736, 1867, 718, 1618, 1883, 604, 225, 1508, 869, 743, 1384, 625, 887, 1784, 891, 1406}, 31: {7, 1034, 1037, 14, 1558, 1815, 1816, 1277, 1306, 1058, 1828, 41, 297, 812, 1581, 301, 1837, 1584, 567, 568, 569, 1339, 574, 1096, 1608, 1098, 1610, 1609, 1102, 79, 1873, 1619, 597, 603, 605, 862, 95, 861, 353, 1378, 609, 356, 613, 1639, 872, 362, 1900, 621, 112, 627, 122, 1915, 123, 1916, 641, 129, 387, 1668, 386, 1159, 1421, 141, 910, 1936, 1425, 669, 926, 159, 1185, 1698, 1699, 1190, 423, 680, 1194, 1963, 1710, 1457, 1459, 1205, 1717, 696, 953, 1208, 189, 701, 706, 707, 710, 1480, 971, 716, 213, 1494, 215, 214, 1499, 737, 482, 483, 1767, 490, 1521, 758, 1015, 1533}, 32: {1029, 19, 1044, 35, 1062, 39, 1067, 1071, 51, 1076, 55, 1080, 1082, 1083, 67, 1092, 1093, 72, 1103, 1109, 1112, 1113, 93, 1120, 101, 1129, 110, 113, 1140, 1141, 118, 117, 120, 1146, 125, 128, 130, 133, 1157, 1160, 139, 1164, 145, 1170, 1173, 168, 176, 1209, 1217, 194, 197, 200, 1224, 1233, 212, 216, 217, 1247, 1248, 227, 1251, 229, 1253, 1254, 1257, 239, 1263, 243, 1271, 256, 1280, 1281, 260, 261, 1290, 269, 1294, 1298, 275, 278, 285, 286, 289, 1320, 304, 1335, 312, 318, 322, 332, 336, 337, 338, 341, 344, 1370, 349, 358, 1385, 1390, 1393, 370, 376, 1402, 1403, 393, 1422, 401, 402, 404, 405, 1432, 408, 1436, 421, 424, 432, 1460, 1461, 1466, 446, 1471, 457, 1484, 472, 1500, 1503, 486, 1511, 1514, 491, 1515, 1517, 1524, 1531, 1535, 1549, 1556, 1570, 547, 555, 565, 1605, 1606, 589, 1620, 1629, 606, 1641, 1644, 1646, 623, 626, 1652, 1654, 631, 1656, 642, 643, 1669, 647, 1675, 1676, 656, 657, 666, 668, 670, 1697, 1700, 677, 1711, 689, 1716, 1718, 1722, 705, 1740, 1743, 721, 1745, 1747, 1751, 1753, 732, 733, 1762, 1769, 746, 747, 1773, 751, 753, 761, 1790, 766, 769, 1794, 778, 785, 789, 790, 792, 799, 800, 803, 1829, 1832, 809, 1833, 811, 813, 1840, 1842, 1843, 1848, 836, 1864, 841, 845, 1869, 1878, 1881, 870, 871, 874, 875, 877, 1908, 1909, 1910, 1912, 1913, 1914, 1917, 1918, 1919, 897, 1921, 899, 1922, 1925, 1924, 1927, 1926, 1929, 1931, 1933, 1935, 912, 913, 1937, 916, 1940, 1941, 1943, 922, 1948, 925, 1950, 1951, 1954, 1955, 1957, 1960, 1961, 1962, 940, 941, 1964, 1967, 944, 955, 966, 968, 973, 976, 991, 993, 995, 998, 1005, 1006, 1007, 1008}, 33: {1920, 382, 3, 782, 1169, 1276, 663, 1180, 1566, 1952, 1956, 1703, 1196, 1203, 1719, 185, 186, 1212, 1214, 1348, 454, 331, 1240, 1375, 1376, 100, 1509, 494, 241, 755, 1907, 380, 892, 894}, 34: {389, 1546, 398, 1808, 17, 148, 535, 920, 664, 156, 414, 163, 1314, 1701, 1577, 1591, 1720, 1730, 1347, 324, 1858, 1352, 713, 719, 343, 1880, 1497, 1250, 1382, 615, 1002, 1130, 1388, 495, 1778, 756, 1023}, 35: {19, 1044, 32, 1062, 1064, 1065, 1067, 1071, 51, 55, 1082, 1083, 63, 1093, 72, 1103, 1109, 1113, 93, 1120, 1121, 1129, 110, 113, 117, 1141, 120, 1146, 128, 130, 133, 1157, 1160, 139, 1164, 1170, 168, 176, 1209, 1217, 194, 197, 200, 1224, 1233, 218, 222, 1247, 1248, 227, 1251, 1253, 1254, 1263, 243, 1271, 1272, 260, 261, 1290, 269, 1294, 1298, 275, 278, 1307, 1308, 285, 286, 289, 1320, 304, 1335, 312, 315, 318, 320, 1351, 336, 337, 338, 344, 1370, 349, 358, 1390, 1393, 370, 376, 393, 1419, 1422, 401, 402, 404, 405, 408, 1436, 421, 1446, 432, 1461, 1467, 446, 1471, 457, 1484, 472, 1500, 1503, 486, 1511, 491, 1515, 1517, 1524, 1535, 1542, 1549, 1556, 536, 1570, 547, 555, 565, 575, 1605, 1606, 588, 1629, 606, 1641, 1644, 1646, 623, 626, 629, 1654, 631, 1656, 1663, 642, 647, 1674, 1675, 1676, 656, 657, 670, 1697, 1700, 677, 685, 1711, 689, 1716, 1718, 705, 1743, 721, 1745, 727, 1751, 1753, 732, 733, 1762, 746, 747, 1773, 751, 753, 1782, 1783, 761, 766, 1790, 769, 1794, 778, 785, 792, 1820, 799, 800, 803, 1829, 809, 1833, 811, 813, 1842, 1843, 1848, 836, 1864, 841, 1869, 1881, 870, 1895, 871, 874, 875, 1908, 1909, 1910, 1912, 1913, 1914, 1917, 1918, 1919, 897, 1921, 899, 1922, 1924, 1925, 1926, 1928, 1929, 1931, 1933, 1935, 912, 913, 914, 1937, 916, 1940, 1941, 1943, 922, 1948, 1949, 925, 1950, 1951, 1954, 1955, 1957, 1960, 1961, 1962, 940, 941, 1964, 1967, 944, 955, 966, 968, 973, 983, 991, 993, 995, 1005, 1006, 1007}, 36: {1222, 1416, 1033, 1162, 1487, 1554, 725, 471, 856, 665, 1244, 1374, 1899, 1774, 1791}, 37: {1792, 257, 1661, 395, 1739, 1772, 1807, 506, 1715, 1046, 762, 1181}, 38: {1569, 1857, 867, 1221, 455, 977, 1363, 1434, 795, 572, 1755, 383}, 39: {1281, 1029, 1549, 1294, 32, 800, 1570, 803, 1840, 1076, 55, 1083, 322, 67, 1092, 1605, 836, 332, 1620, 341, 1878, 1112, 1113, 344, 358, 874, 1140, 1141, 118, 1652, 1908, 376, 1402, 1914, 125, 1918, 128, 897, 1921, 393, 1931, 1422, 1935, 912, 145, 401, 402, 916, 1173, 405, 1940, 1941, 666, 668, 1948, 1951, 1954, 168, 424, 1960, 941, 1967, 432, 1460, 1722, 955, 1484, 721, 1747, 212, 216, 472, 732, 733, 991, 1248, 227, 1251, 1253, 1769, 746, 1514, 1005, 1517, 239, 1007, 1524, 1531, 1535}, 40: {160, 1313, 578, 1344, 884, 23, 1625, 507, 447}, 41: {1668, 423, 297, 141, 14, 1581, 112, 1521, 758, 215, 862, 31}, 42: {481, 1230, 1265, 530, 498, 1435, 927}, 43: {1409, 6, 1673, 147, 403, 277, 537, 1564, 158, 1694, 1316, 165, 1444, 169, 174, 1329, 1077, 695, 1594, 1595, 444, 1851, 1095, 73, 844, 1104, 1107, 86, 601, 1505, 1126, 1383, 744, 1645, 1009, 1269, 503}, 44: {450, 453, 456, 460, 205, 911, 274, 658, 1428, 533, 662, 791, 1431, 1433, 723, 858, 1114, 1439, 735, 1830, 359, 105, 107, 47, 1648, 1014, 1593, 1085, 127}, 45: {1920, 321, 1796, 1348, 837, 135, 1292, 1105, 1689, 859, 1695, 1952, 1256, 1708, 1714, 1013, 1597, 1278}, 46: {769, 258, 515, 516, 260, 1289, 525, 1045, 793, 1054, 287, 799, 547, 548, 803, 1062, 1320, 553, 809, 811, 300, 1071, 1842, 563, 565, 55, 1335, 1082, 829, 318, 319, 1342, 1860, 1093, 582, 1861, 840, 1864, 337, 1109, 1113, 345, 93, 350, 96, 355, 871, 616, 875, 1644, 623, 367, 626, 370, 1909, 1654, 1910, 120, 1146, 1914, 1917, 1918, 130, 642, 1155, 645, 1157, 1922, 899, 1924, 1925, 139, 1675, 1676, 142, 1926, 1415, 1929, 1420, 1933, 912, 1937, 915, 1943, 408, 925, 670, 1950, 1697, 1954, 421, 1957, 1961, 1962, 940, 1964, 1711, 177, 689, 1716, 1718, 705, 963, 966, 1224, 459, 1743, 1232, 721, 1745, 733, 1247, 1759, 1503, 486, 1511, 747, 1517, 751, 1780, 1524, 1535}, 47: {450, 453, 456, 460, 205, 911, 274, 658, 1428, 533, 662, 791, 1431, 1433, 723, 858, 1114, 1439, 735, 1830, 359, 105, 107, 44, 1648, 1014, 1593, 1085, 127}, 48: {1, 2, 198, 1543, 1799, 1800, 585, 269, 909, 1361, 614, 1452, 1004, 109, 1330, 1017, 317, 1855}, 49: {608, 390, 166, 1319, 1742, 880, 564, 373, 661, 1852, 671}, 50: {385, 898, 1410, 1545, 1911, 1304, 1184, 932, 1450, 308, 1336, 1592, 703, 1215, 1599, 1733, 711, 1099, 76, 1870, 847, 339, 340, 1625, 731, 221, 994, 233, 1138, 1395, 1396, 1143, 1149}, 51: {1549, 1044, 1556, 32, 1570, 35, 547, 1062, 555, 1067, 1071, 565, 1082, 1083, 1093, 1605, 72, 1103, 1109, 1113, 93, 606, 1629, 1120, 1129, 1644, 110, 623, 1646, 113, 626, 117, 1141, 631, 120, 1654, 1146, 1656, 128, 130, 642, 133, 1157, 647, 1160, 139, 1164, 1675, 1676, 656, 657, 1170, 670, 1697, 1700, 677, 168, 1711, 176, 689, 1716, 1718, 1209, 705, 194, 197, 200, 1224, 1743, 721, 1233, 1745, 1751, 1753, 732, 733, 1247, 1248, 1762, 1251, 1254, 746, 747, 1773, 751, 1263, 753, 243, 1271, 761, 766, 1790, 769, 1794, 260, 261, 778, 1290, 269, 1294, 785, 1298, 275, 278, 792, 285, 286, 799, 800, 289, 803, 1829, 1320, 809, 1833, 811, 813, 304, 1842, 1843, 1335, 312, 1848, 318, 836, 1864, 841, 1869, 337, 338, 344, 1881, 1370, 349, 358, 870, 871, 874, 875, 1390, 1393, 370, 1908, 1909, 1910, 376, 1912, 1913, 1914, 1917, 1918, 1919, 897, 1921, 899, 1922, 1924, 1925, 1926, 393, 1929, 1931, 1933, 1422, 1935, 912, 401, 402, 913, 404, 405, 916, 1937, 408, 1940, 922, 1941, 1436, 925, 1943, 1950, 1951, 1954, 1955, 421, 1957, 1960, 1961, 1962, 940, 941, 1964, 1967, 432, 944, 1461, 446, 1471, 966, 457, 1484, 973, 472, 1500, 991, 1503, 993, 995, 486, 1511, 491, 1515, 1005, 1517, 1524, 1535}, 52: {64, 134, 1862, 720, 1553, 1680, 1115, 1438, 1310, 1377, 235, 1580, 749, 501, 504, 1274}, 53: {1664, 1282, 646, 1287, 1417, 143, 1424, 1427, 152, 1177, 1189, 1192, 682, 1451, 686, 1200, 305, 820, 950, 1081, 1721, 62, 1344, 325, 76, 593, 466, 339, 1625, 1371, 1628, 1506, 233, 873, 238, 622, 878, 754, 1396, 1142, 1911}, 54: {772, 1604, 328, 904, 1936, 851, 1622, 409, 862, 1765, 807, 808, 361, 234, 1397, 630, 250}, 55: {515, 516, 1029, 1542, 1935, 525, 1549, 19, 1045, 536, 1054, 32, 1570, 547, 548, 35, 1062, 39, 1064, 553, 1065, 46, 1071, 563, 1076, 565, 1082, 1083, 575, 63, 67, 1092, 1093, 582, 1605, 1606, 588, 1620, 1109, 1112, 1113, 93, 96, 1121, 616, 1129, 1641, 1644, 623, 626, 1140, 117, 1654, 629, 120, 1141, 1146, 118, 1652, 125, 1663, 128, 130, 642, 1155, 645, 1157, 1674, 139, 1675, 1676, 142, 145, 1173, 666, 668, 670, 1697, 168, 685, 1711, 177, 689, 1716, 1718, 1722, 705, 1217, 1224, 1743, 1232, 721, 1745, 1747, 212, 727, 216, 218, 732, 733, 222, 1247, 1759, 1248, 227, 1251, 1253, 1769, 746, 747, 751, 239, 1780, 1782, 1783, 1272, 769, 258, 1794, 260, 1281, 1289, 1294, 785, 793, 1307, 1308, 1820, 287, 799, 800, 803, 1320, 809, 811, 300, 1840, 1842, 1335, 315, 829, 318, 319, 1342, 320, 322, 1860, 1861, 836, 1351, 840, 1864, 332, 336, 337, 341, 1878, 344, 345, 350, 355, 358, 871, 1895, 874, 875, 367, 1393, 370, 1908, 1909, 1910, 1912, 376, 1914, 1402, 1917, 1918, 897, 1922, 899, 1924, 1925, 1926, 1415, 1928, 1929, 1921, 1419, 1420, 1933, 393, 1931, 912, 1937, 402, 915, 914, 405, 916, 1943, 408, 401, 1940, 1941, 1948, 925, 1950, 1949, 1951, 1954, 421, 1957, 1446, 1960, 1961, 1962, 424, 940, 1964, 941, 1967, 432, 1460, 955, 1467, 963, 966, 968, 457, 459, 1484, 973, 983, 472, 1503, 991, 486, 1511, 1514, 1517, 1005, 1007, 1006, 1422, 1524, 1531, 1535}, 56: {709, 970, 1357, 974, 1871, 1237, 1241, 1119, 1057, 554, 1322, 561, 1267, 61, 1462, 1275, 1021}, 57: {1537, 1284, 1476, 1414, 681, 505, 1582, 694, 1302, 1048, 573, 831}, 58: {1568, 1091, 1590, 1686, 1051, 798}, 59: {1031, 266, 1483, 270, 1678, 528, 784, 659, 928, 676, 102, 679, 1894, 1586, 628, 1398, 188, 126}, 60: {1571, 388, 1735, 1288, 429, 945, 210, 83, 562, 566, 415}, 61: {709, 970, 1357, 974, 1871, 1237, 1241, 1119, 1057, 554, 1322, 561, 1267, 1462, 56, 1275, 1021}, 62: {1664, 1282, 646, 1287, 1417, 143, 1424, 1427, 152, 1177, 1189, 1192, 682, 1451, 686, 1200, 305, 820, 53, 950, 1081, 1721, 1344, 325, 76, 593, 466, 339, 1625, 1371, 1628, 1506, 233, 873, 238, 622, 878, 754, 1396, 1142, 1911}, 63: {1794, 1542, 1294, 785, 19, 536, 1307, 1308, 1820, 800, 35, 1064, 1065, 55, 575, 320, 836, 1605, 1351, 588, 336, 1121, 1895, 1129, 1641, 1393, 117, 629, 1912, 1914, 1917, 1663, 1928, 1674, 1419, 402, 914, 916, 405, 1948, 1949, 1446, 168, 1960, 685, 1967, 955, 1467, 1217, 968, 457, 973, 1743, 727, 983, 218, 732, 733, 222, 227, 1253, 746, 1005, 1006, 1782, 1783, 1272}, 64: {134, 1862, 720, 1553, 1680, 1115, 1438, 1310, 1377, 235, 1580, 749, 52, 501, 504, 1274}, 65: {192, 1824, 1920, 1719, 1196, 879, 1207, 1240, 1178, 284, 540}, 66: {898, 804, 5, 1892, 1128, 1545, 654, 1200, 466, 339, 1138, 1906, 1911, 830}, 67: {1281, 1029, 1549, 1294, 32, 800, 1570, 803, 39, 1840, 1076, 55, 1083, 322, 1092, 1605, 836, 332, 1620, 341, 1878, 1112, 1113, 344, 358, 874, 1140, 1141, 118, 1652, 1908, 376, 1402, 1914, 125, 1918, 128, 897, 1921, 393, 1931, 1422, 1935, 912, 145, 401, 402, 916, 1173, 405, 1940, 1941, 666, 668, 1948, 1951, 1954, 168, 424, 1960, 941, 1967, 432, 1460, 1722, 955, 1484, 721, 1747, 212, 216, 472, 732, 733, 991, 1248, 227, 1251, 1253, 1769, 746, 1514, 1005, 1517, 239, 1007, 1524, 1531, 1535}, 68: {1944, 1945, 1946, 1932}, 69: {1728, 1572, 1445, 587, 173, 750, 272, 1776, 531, 87, 1626, 1246}, 70: {1200, 865, 1906, 339, 1911}, 71: {1538, 1667, 1028, 1672, 265, 397, 527, 1167, 1295, 794, 538, 157, 29, 544, 1279, 1579, 1709, 1841, 818, 182, 310, 1334, 1470, 1600, 1475, 1607, 1097, 1485, 82, 1746, 469, 986, 91, 1630, 1760, 230, 1000, 237, 366, 1518, 1139, 1523, 1150, 511}, 72: {1549, 1044, 1556, 32, 1570, 35, 547, 1062, 555, 1067, 1071, 51, 565, 1082, 1083, 1093, 1605, 1103, 1109, 1113, 93, 606, 1629, 1120, 1129, 1644, 110, 623, 1646, 113, 626, 117, 1141, 631, 120, 1654, 1146, 1656, 128, 130, 642, 133, 1157, 647, 1160, 139, 1164, 1675, 1676, 656, 657, 1170, 670, 1697, 1700, 677, 168, 1711, 176, 689, 1716, 1718, 1209, 705, 194, 197, 200, 1224, 1743, 721, 1233, 1745, 1751, 1753, 732, 733, 1247, 1248, 1762, 1251, 1254, 746, 747, 1773, 751, 1263, 753, 243, 1271, 761, 766, 1790, 769, 1794, 260, 261, 778, 1290, 269, 1294, 785, 1298, 275, 278, 792, 285, 286, 799, 800, 289, 803, 1829, 1320, 809, 1833, 811, 813, 304, 1842, 1843, 1335, 312, 1848, 318, 836, 1864, 841, 1869, 337, 338, 344, 1881, 1370, 349, 358, 870, 871, 874, 875, 1390, 1393, 370, 1908, 1909, 1910, 376, 1912, 1913, 1914, 1917, 1918, 1919, 897, 1921, 899, 1922, 1924, 1925, 1926, 393, 1929, 1931, 1933, 1422, 1935, 912, 401, 402, 913, 404, 405, 916, 1937, 408, 1940, 922, 1941, 1436, 925, 1943, 1950, 1951, 1954, 1955, 421, 1957, 1960, 1961, 1962, 940, 941, 1964, 1967, 432, 944, 1461, 446, 1471, 966, 457, 1484, 973, 472, 1500, 991, 1503, 993, 995, 486, 1511, 491, 1515, 1005, 1517, 1524, 1535}, 73: {1409, 6, 1673, 147, 403, 277, 537, 1564, 158, 1694, 1316, 165, 1444, 169, 43, 174, 1329, 1077, 695, 1594, 1595, 444, 1851, 1095, 844, 1104, 1107, 86, 601, 1505, 1126, 1383, 744, 1645, 1009, 1269, 503}, 74: {736, 1729, 451, 1478, 1683, 436, 119, 1723, 223}, 75: {919, 1836, 1789, 895}, 76: {1664, 385, 1282, 898, 1410, 646, 1287, 1417, 1545, 143, 1424, 1427, 152, 1177, 1304, 1184, 932, 1189, 1192, 682, 1451, 1450, 686, 1200, 305, 50, 820, 53, 950, 308, 1336, 1081, 1721, 1592, 62, 703, 1344, 1215, 1599, 325, 1733, 711, 1099, 1870, 847, 593, 466, 339, 340, 1143, 1625, 1371, 1628, 731, 221, 1506, 994, 233, 873, 238, 622, 878, 754, 1138, 1396, 1395, 1142, 1911, 1149}, 77: {1089, 1218, 580, 1220, 839, 1165, 1614, 207, 208, 1303, 26, 1243, 1469, 485, 1068, 633, 1844, 821, 502, 1337, 508, 1213}, 78: {512, 1920, 1731, 1348, 392, 1210, 522, 907, 842, 638, 978, 917, 982, 1372, 1117, 478, 1824, 480, 1761, 1635, 1764, 933, 294, 1069, 1262, 1011, 1907, 698, 958}, 79: {7, 1034, 1037, 1558, 1816, 1277, 31, 1058, 1828, 812, 1584, 568, 569, 1339, 574, 1096, 1608, 1098, 1610, 1102, 1873, 597, 605, 862, 95, 1378, 356, 1639, 872, 1900, 621, 112, 1915, 123, 1916, 641, 387, 1421, 926, 159, 1185, 1699, 1190, 680, 1194, 1710, 1459, 1205, 1717, 696, 953, 1208, 189, 701, 707, 710, 1480, 971, 716, 215, 1499, 737, 483, 1767, 1015, 1533}, 80: {1156, 1285, 136, 776, 138, 1354, 81, 1426, 596, 1111, 1239, 1305, 729, 27, 1116, 1373, 1249, 1442, 1640, 108, 817, 951, 632, 1273}, 81: {1156, 1285, 136, 776, 138, 1354, 80, 1426, 596, 1111, 1239, 1305, 729, 27, 1116, 1373, 1249, 1442, 1640, 108, 817, 951, 632, 1273}, 82: {1538, 1667, 1028, 1672, 265, 397, 527, 1167, 1295, 794, 538, 157, 29, 544, 1279, 1579, 1709, 1841, 818, 182, 310, 1334, 1470, 1600, 1475, 71, 1607, 1097, 1485, 1746, 469, 986, 91, 1630, 1760, 230, 1000, 237, 366, 1518, 1139, 1523, 1150, 511}, 83: {1571, 388, 1735, 1288, 429, 945, 210, 562, 566, 60, 415}, 84: {1345, 835, 1541, 8, 10, 140, 204, 1358, 783, 1041, 18, 1106, 346, 220, 92, 1890, 293, 1191, 937, 748, 876, 1333, 888, 1465, 1534}, 85: {1153, 1411, 648, 267, 526, 1806, 406, 1559, 1179, 543, 822, 1846, 956, 1725, 191, 1216, 201, 330, 203, 458, 1100, 206, 590, 464, 1611, 853, 1885, 1118, 610, 741, 232, 1647, 1136, 881, 1650, 116, 500, 1530}, 86: {1409, 6, 1673, 147, 403, 277, 537, 1564, 158, 1694, 1316, 165, 1444, 169, 43, 174, 1329, 1077, 695, 1594, 1595, 444, 

Let us now create a csv of edges connecting the ids that are coauthors.

In [33]:
coauthors_df = pd.DataFrame()
sources = []
targets = []
for key, val in source_to_related_sources.items():
    for item in val:
        sources.append(key)
        targets.append(item)

edge_name = ["coauthors"] * len(sources)

coauthors_df['source'] = sources
coauthors_df['relation'] = edge_name
coauthors_df['target'] = targets


coauthors_df.to_csv(path_to_folder + "authors.coauthors.authors.edges.csv", 
                    index=False)

In [34]:
authors = pd.read_csv(path_to_folder + "authors.nodes.csv")

In [35]:
authors

,id,label,PMIDS,affiliation
0,0,A M Maga,36802342;39554050,(Center for Developmental Biology and Regenera...
1,1,Aaron Goldman,38926365,"(Molecular and Cellular Oncogenesis Program, T..."
2,2,Aaron Havas,38926365,(Sanford Burnham Prebys Medical Discovery Inst...
3,3,Aaron W Puri,34862502,"(Department of Chemistry, University of Utah, ..."
4,4,Abhijith Asok,36350676,"(Microsoft Inc. Redmond, WA, USA.)"
...,...,...,...,...
1964,1964,Yu Jiang,30643251;36477530,"(Department of Public Health Sciences, College..."
1965,1965,Yufei Huang,38313267;38370127,"(Department of Medicine, University of Pittsbu..."
1966,1966,Yuin-Han Loh,37657444;39149248;39562549,"(Cell Fate Engineering and Therapeutics Lab, C..."
1967,1967,Brian E Cade,31964835;35927319;36303018;36477530;36564505,"(Division of Sleep and Circadian Disorders, Br..."
1968,1968,Dean P Jones,38544285;38651675;38984754,"(Division of Pulmonary, Allergy, Critical Care..."

In [40]:
# Function to transform the name format
def transform_name(name):
    parts = name.split()
    last_name = parts[-1]  # Last part is the surname
    first_names = ' '.join(parts[:-1])  # Everything else is the first/middle names
    return f"{last_name}, {first_names}"

In [41]:
authors['Name'] = authors['label'].apply(transform_name)

In [42]:
authors

,id,label,PMIDS,affiliation,Name
0,0,A M Maga,36802342;39554050,(Center for Developmental Biology and Regenera...,"Maga, A M"
1,1,Aaron Goldman,38926365,"(Molecular and Cellular Oncogenesis Program, T...","Goldman, Aaron"
2,2,Aaron Havas,38926365,(Sanford Burnham Prebys Medical Discovery Inst...,"Havas, Aaron"
3,3,Aaron W Puri,34862502,"(Department of Chemistry, University of Utah, ...","Puri, Aaron W"
4,4,Abhijith Asok,36350676,"(Microsoft Inc. Redmond, WA, USA.)","Asok, Abhijith"
...,...,...,...,...,...
1964,1964,Yu Jiang,30643251;36477530,"(Department of Public Health Sciences, College...","Jiang, Yu"
1965,1965,Yufei Huang,38313267;38370127,"(Department of Medicine, University of Pittsbu...","Huang, Yufei"
1966,1966,Yuin-Han Loh,37657444;39149248;39562549,"(Cell Fate Engineering and Therapeutics Lab, C...","Loh, Yuin-Han"
1967,1967,Brian E Cade,31964835;35927319;36303018;36477530;36564505,"(Division of Sleep and Circadian Disorders, Br...","Cade, Brian E"
1968,1968,Dean P Jones,38544285;38651675;38984754,"(Division of Pulmonary, Allergy, Critical Care...","Jones, Dean P"

In [43]:
authors.to_csv(path_to_folder + "authors.nodes.csv")